spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: user1
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  mvc:
    servlet:
      load-on-startup: 1